Repository prgrms-fe-devcourse/FEDC2_GreenButler_Off, pull requests merged in 2022-06, with the labels that each got.

#12 feat: Image 컴포넌트 구현
  src/components/basic/Image/index.jsx
  src/stories/basic/Image.stories.jsx
Labels: 피드백 요청

#96 feat: Profile 컴포넌트 추가
  src/components/Profile/index.jsx
  src/components/basic/Text/index.jsx
  src/utils/constants/images.js
Labels: 피드백 요청, 🌵보통

#94 feature: IconButton, IconLink 컴포넌트 추가
  src/components/basic/Icon/IconButton.jsx
  src/components/basic/Icon/IconLink.jsx
  src/components/basic/Icon/index.jsx
  src/styles/index.css
Labels: 🌵보통

#95 feat: 회원가입 로직 수정
  src/contexts/UserContext/handles.jsx
  src/pages/SignupPage/index.jsx
Labels: 🌵보통

#100 refactor: PageWrapper 내부에 Header, Navigation 추가
  src/components/Header/Header.jsx
  src/components/Navigation/index.jsx
  src/components/basic/pageWrapper/index.js
  src/pages/PostAddPage/index.jsx
  src/pages/SearchPage/index.jsx
  src/pages/SearchTagPage/index.jsx
  src/template/DefaultTemplate.jsx
Labels: 🌼피드백 요청, 🌵보통

#102 feat: 포스트에 더보기 버튼 추가
  src/pages/MainPage/PostBody.jsx
  src/pages/MainPage/PostHeader.jsx
  src/pages/MainPage/PostItem.jsx
  src/pages/MainPage/index.jsx
  src/pages/PostDetailPage/PostDetail.jsx
  src/pages/PostDetailPage/index.jsx
Labels: 🌵보통

#108 refactor: PostAddPage 실제 유저 토큰 연결
  src/pages/PostAddPage/index.jsx
  src/utils/apis/postApi.js
Labels: 🌵보통

#105 refactor: Tab 컴포넌트 아이콘 추가 기능 구현
  src/components/UserSearchResult/FollowBtn.jsx
  src/components/UserSearchResult/FollowingBtn.jsx
  src/components/UserSearchResult/index.jsx
  src/components/basic/Button/index.jsx
  src/components/basic/Tab/TabItem.jsx
  src/pages/SearchPage/index.jsx
  src/utils/apis/postApi.js
Labels: 🌵보통

#118 feat: MainPage 무한스크롤 추가
  src/pages/MainPage/PostBody.jsx
  src/pages/MainPage/index.jsx
Labels: 🌵보통

#116 feat: Modal 컴포넌트 구현
  src/components/Modal/ModalButton.jsx
  src/components/Modal/ModalContent.jsx
  src/components/Modal/index.jsx
  src/components/basic/Button/index.jsx
  src/components/basic/Text/index.jsx
  src/hooks/useClickAway.js
  src/stories/Modal.stories.jsx
  src/styles/theme.js
  src/utils/constants/images.js
Labels: 🌵보통

#120 refactor: Modal 컴포넌트에 다른 컴포넌트 추가할 수 있도록 변경
  public/index.html
  src/components/Modal/ModalCustom.jsx
  src/components/Modal/index.jsx
Labels: 🌵보통

#129 style: pageWrapper 추가 및 width 작업
  src/pages/LoginPage/index.jsx
  src/pages/SignupPage/index.jsx
Labels: 🌵보통

#127 Refactor/follow
  src/components/ChangePasswordForm/index.jsx
  src/components/FollowList/MyFollowList.jsx
  src/components/FollowList/index.jsx
  src/components/Navigation/index.jsx
  src/components/PostImageContainer/index.jsx
  src/components/basic/Input/index.jsx
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
  src/pages/FollowPage/index.jsx
  src/pages/MyInfoEditPage/index.jsx
  src/pages/MyInfoPage/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/MyPage/style.jsx
  src/pages/UserPage/index.jsx
  src/pages/UserPage/style.jsx
  src/routes/Router.jsx
  src/utils/apis/userApi.js
Labels: 🌵보통

#130 feat: Notification Page 구현
  src/components/Card/index.jsx
  src/components/NotificationCard/index.jsx
  src/pages/NotificationPage/index.jsx
Labels: 🌵보통

#141 feat: 포스트 삭제 및 알람 기능 추가 등
  src/pages/MainPage/PostBody.jsx
  src/pages/MainPage/PostHeader.jsx
  src/pages/MainPage/PostItem.jsx
  src/pages/PostDetailPage/index.jsx
  src/routes/Router.jsx
  src/utils/apis/userApi.js
  src/utils/functions/displayedAt.js
Labels: 🔥긴급

#135 feature: 게시글 작성 페이지(PostAddPage) textarea 자동 높이 조절 추가
  src/components/basic/pageWrapper/index.js
  src/pages/PostAddPage/index.jsx
Labels: 🌵보통

#136 feature: 게시글 수정 페이지(postEditPage) 구현
  src/components/PostTextArea/index.jsx
  src/components/UploadImage/index.jsx
  src/pages/PostAddPage/index.jsx
  src/pages/PostEditPage/index.jsx
  src/routes/Router.jsx
  src/utils/apis/postApi.js
Labels: 🌵보통

#145 refactor: follow페이지 수정
  src/components/FollowList/MyFollowList.jsx
  src/contexts/UserContext/handles.jsx
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
Labels: 🔥긴급

#133 refactor(MyInfo): 로그아웃 모달 추가 및 컴포넌트 분리
  src/pages/MyInfoEditPage/index.jsx
  src/pages/MyInfoPage/UserDetails.jsx
  src/pages/MyInfoPage/UserProfile.jsx
  src/pages/MyInfoPage/index.jsx
  src/pages/MyPage/index.jsx
Labels: 🌵보통

#134 feat: 로그인 / 회원가입 Modal 컴포넌트 수정
  src/contexts/UserContext/handles.jsx
  src/pages/LoginPage/index.jsx
  src/pages/SignupPage/index.jsx
Labels: 🌵보통

#140 refactor: page-style
  src/components/Card/index.jsx
  src/components/LoginForm/index.jsx
  src/components/NotificationCard/index.jsx
  src/components/SignupForm/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/NotificationPage/index.jsx
Labels: 🌵보통

#142 refactor: getUserLevel 함수가 score도 반환하도록 수정
  src/utils/functions/userLevel/getUserLevel.js
Labels: 🌵보통

#143 feat: 알림 확인 처리 API 추가
  src/utils/apis/postApi.js
Labels: 🌵보통

#148 fix: MyInfo 최종 사항 반영
  src/components/Navigation/index.jsx
  src/components/PostImageContainer/index.jsx
  src/components/TagSearchResult/index.jsx
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
  src/pages/MyInfoPage/UserDetails.jsx
  src/pages/MyInfoPage/UserProfile.jsx
  src/pages/MyPage/index.jsx
  src/pages/MyPage/style.jsx
  src/pages/UserPage/index.jsx
  src/pages/UserPage/style.jsx
  src/pages/index.jsx
  src/routes/Router.jsx
Labels: 🔥긴급

#154 feature: 로그인 유지 기능 추가
  src/contexts/UserContext/handles.jsx
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
  src/contexts/UserContext/types.jsx
  src/hooks/useLocalToken.jsx
  src/pages/MainPage/PostBody.jsx
  src/routes/Router.jsx
Labels: 🌼피드백 요청, 🔥긴급

#149 feat: Notification 스타일 / 링크 / 프로필 이미지 수정
  src/components/Card/index.jsx
  src/components/NotificationCard/index.jsx
  src/pages/NotificationPage/index.jsx
Labels: 🌵보통

#152 refactor: 게시글 수정 페이지(post edit page) state 연결
  src/components/Header/Header.jsx
  src/components/TagAddForm/index.jsx
  src/components/TagSearchResult/index.jsx
  src/hooks/useValidInput.js
  src/pages/PostEditPage/index.jsx
Labels: 🌵보통

#155 Feature: 유저 정보 페이지에 유저 활동 점수 및 등급 확인 기능 추가
  src/pages/MyInfoPage/LevelModal.jsx
  src/pages/MyInfoPage/UserLevel.jsx
  src/pages/MyInfoPage/index.jsx
  src/utils/constants/icons/index.js
  src/utils/functions/userLevel/getUserLevel.js
  src/utils/functions/userLevel/levels.js
Labels: 🌵보통

#157 fix: UserPage 최종수정
  src/components/Navigation/index.jsx
  src/components/PostImageContainer/index.jsx
  src/components/basic/Input/index.jsx
  src/contexts/UserContext/handles.jsx
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
  src/pages/UserPage/UserData.jsx
  src/pages/UserPage/index.jsx
  src/pages/UserPage/style.jsx
  src/stories/components/PostImageContainer.stories.jsx
  src/stories/components/PostImageList.stories.jsx
  src/utils/constants/icons/names.js
  src/utils/constants/images.js
  src/utils/functions/userLevel/getUserLevel.js
Labels: 🌵보통

#160 Refactor/post detail
  src/pages/MainPage/PostBody.jsx
  src/pages/MainPage/PostHeader.jsx
  src/pages/PostDetailPage/index.jsx
Labels: 🌵보통

#163 fix: UserPage & MyInfo 수정 반영
  src/components/PostImageContainer/index.jsx
  src/contexts/UserContext/handles.jsx
  src/contexts/UserContext/index.jsx
  src/pages/MyInfoEditPage/index.jsx
  src/pages/UserPage/UserData.jsx
  src/pages/UserPage/index.jsx
  src/pages/UserPage/style.jsx
  src/utils/apis/userApi.js
Labels: 🌵보통

#173 refactor: 모달 메시지 수정
  src/pages/LoginPage/index.jsx
  src/pages/SignupPage/index.jsx
Labels: 🌵보통

#174 deploy: 6차 배포
  public/_redirects
  src/contexts/UserContext/reducer.jsx
  src/pages/LoginPage/index.jsx
  src/pages/SignupPage/index.jsx
Labels: 🌷배포

#177 deploy: 7차 배포
  public/favicon.ico
  public/index.html
  src/pages/PostEditPage/index.jsx
  src/pages/SearchPage/UserSearchResult.jsx
Labels: 🌷배포

#179 refactor/token og
  public/index.html
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
  src/hooks/useLocalStrorage.js
  src/hooks/useLocalToken.jsx
  src/pages/SignupPage/index.jsx
Labels: 🌵보통

#182 hotfix: .HEIC 이미지 로드 에러 수정
  src/components/PostImageContainer/index.jsx
  src/components/basic/Avatar/index.jsx
  src/components/basic/Image/index.jsx
  src/pages/MainPage/PostBody.jsx
Labels: 🌵보통

#188 refactor: SignupModal description 분리
  src/pages/SignupPage/index.jsx
Labels: 🌵보통

#190 deploy: 8차 배포
  public/index.html
  src/components/Modal/ModalContent.jsx
  src/components/PostImageContainer/index.jsx
  src/components/SignupForm/index.jsx
  src/components/TagAddForm/index.jsx
  src/components/UploadImage/index.jsx
  src/components/basic/Avatar/index.jsx
  src/components/basic/Image/index.jsx
  src/contexts/UserContext/handles.jsx
  src/contexts/UserContext/index.jsx
  src/contexts/UserContext/reducer.jsx
  src/contexts/UserContext/types.jsx
  src/hooks/useLocalToken.js
  src/hooks/useScrollPosition.js
  src/hooks/useScrollToTop.js
  src/hooks/useSessionStorage.js
  src/hooks/useValidInputs.js
  src/pages/MainPage/PostBody.jsx
  src/pages/MainPage/PostItem.jsx
  src/pages/MainPage/index.jsx
  src/pages/PostDetailPage/index.jsx
  src/pages/PostEditPage/index.jsx
  src/pages/SignupPage/index.jsx
  src/pages/UserPage/index.jsx
  src/pages/UserPage/style.jsx
  src/routes/Router.jsx
  src/template/DefaultTemplate.jsx
  src/utils/apis/common.js
  src/utils/storage/sessionStorage.js
Labels: 🌷배포
